on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-verision: '12.x'
    - run : npm run lint